### ISSUE TITLE
Deploy to a local IIS cluster instead of Azure

### ISSUE THREAD

**Issue by ncecere** [covidsafe/Backend#37]
I was wondering if it is possible to deploy the backend to a local environment or if anyone was planing on developing that option.  My university currently does not have the ability to deploy this application to azure but we would love to set it up in our local vsphere environment.

**Comment by corygehr** [comment]
@ncecere shouldn't be any issue with deploying to IIS directly; the default option when running locally is IIS Express.

The challenge is DBMS selection. In the current state we're using Azure CosmosDB because it works at a large scale. I strongly recommend looking at the [Changing DBMS](https://github.com/covidsafe/Backend/wiki/Changing-DBMS) wiki article for instructions on instrumenting a different DBMS (e.g. SQL Server).
